In [182]:
import numpy as np
import pandas as pd 
import matplotlib.pyplot as plt
import seaborn as sns
from matplotlib import cm
from IPython.display import display,HTML
from datetime import datetime
from dateutil.parser import parse
# reading data files
Ind_Aus_Bow_wkts_2years = pd.read_csv("C:\\Users\\sushanth\\Desktop\\Ind_Aus_Bow_wkts_2years.csv", sep=",", header = 0, engine='python', encoding ="utf-8", skipinitialspace=True)
Ind_Aus_Bow_wkts_2years_2 = pd.read_csv("C:\\Users\\sushanth\\Desktop\\Ind_Aus_Bow_wkts_2years_2.csv", sep=",", header = 0, engine='python', encoding ="utf-8", skipinitialspace=True)
Ind_Aus_Bow_wkts_2years_3 = pd.read_csv("C:\\Users\\sushanth\\Desktop\\Ind_Aus_Bow_wkts_2years_3.csv", sep=",", header = 0, engine='python', encoding ="utf-8", skipinitialspace=True)
Ind_Aus_Bow_wkts_2years_4 = pd.read_csv("C:\\Users\\sushanth\\Desktop\\Ind_Aus_Bow_wkts_2years_4.csv", sep=",", header = 0, engine='python', encoding ="utf-8", skipinitialspace=True)
Ind_Aus_Bow_wkts_2years_5 = pd.read_csv("C:\\Users\\sushanth\\Desktop\\Ind_Aus_Bow_wkts_2years_5.csv", sep=",", header = 0, engine='python', encoding ="utf-8", skipinitialspace=True)
Ind_Aus_Bow_wkts_2years_6 = pd.read_csv("C:\\Users\\sushanth\\Desktop\\Ind_Aus_Bow_wkts_2years_6.csv", sep=",", header = 0, engine='python', encoding ="utf-8", skipinitialspace=True)
Ind_Aus_Bow_wkts_2years_7 = pd.read_csv("C:\\Users\\sushanth\\Desktop\\Ind_Aus_Bow_wkts_2years_7.csv", sep=",", header = 0, engine='python', encoding ="utf-8", skipinitialspace=True)
Ind_Aus_Bow_wkts_2years_8 = pd.read_csv("C:\\Users\\sushanth\\Desktop\\Ind_Aus_Bow_wkts_2years_8.csv", sep=",", header = 0, engine='python', encoding ="utf-8", skipinitialspace=True)
Ind_Aus_Bow_wkts_2years_9 = pd.read_csv("C:\\Users\\sushanth\\Desktop\\Ind_Aus_Bow_wkts_2years_9.csv", sep=",", header = 0, engine='python', encoding ="utf-8", skipinitialspace=True)

Ind_Bow_wkts_4years_home = pd.read_csv("C:\\Users\\sushanth\\Desktop\\Ind_Bow_wkts_4years_home.csv", sep=",", header = 0, engine='python', encoding ="utf-8", skipinitialspace=True)
Ind_Bow_wkts_4years_home_2 = pd.read_csv("C:\\Users\\sushanth\\Desktop\\Ind_Bow_wkts_4years_home_2.csv", sep=",", header = 0, engine='python', encoding ="utf-8", skipinitialspace=True)
Ind_Bow_wkts_4years_home_3 = pd.read_csv("C:\\Users\\sushanth\\Desktop\\Ind_Bow_wkts_4years_home_3.csv", sep=",", header = 0, engine='python', encoding ="utf-8", skipinitialspace=True)
Ind_Bow_wkts_4years_home_4 = pd.read_csv("C:\\Users\\sushanth\\Desktop\\Ind_Bow_wkts_4years_home_4.csv", sep=",", header = 0, engine='python', encoding ="utf-8", skipinitialspace=True)



Aus_India_Bow_wkts_10years_selected_venues = pd.read_csv("C:\\Users\\sushanth\\Desktop\\Aus_India_Bow_wkts_10years_selected_venues.csv", sep=",", header = 0, engine='python', encoding ="utf-8", skipinitialspace=True)
Aus_India_Bow_wkts_10years_selected_venues_2 = pd.read_csv("C:\\Users\\sushanth\\Desktop\\Aus_India_Bow_wkts_10years_selected_venues_2.csv", sep=",", header = 0, engine='python', encoding ="utf-8", skipinitialspace=True)
Aus_India_Bow_wkts_10years_selected_venues_3 = pd.read_csv("C:\\Users\\sushanth\\Desktop\\Aus_India_Bow_wkts_10years_selected_venues_3.csv", sep=",", header = 0, engine='python', encoding ="utf-8", skipinitialspace=True)
Aus_India_Bow_wkts_10years_selected_venues_4 = pd.read_csv("C:\\Users\\sushanth\\Desktop\\Aus_India_Bow_wkts_10years_selected_venues_4.csv", sep=",", header = 0, engine='python', encoding ="utf-8", skipinitialspace=True)

In [183]:
Ind_Aus_Bow_wkts_2years.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 11 columns):
Unnamed: 0    0 non-null float64
Econ          50 non-null float64
Ground        50 non-null object
Inns          50 non-null int64
Mdns          50 non-null int64
Opposition    50 non-null object
Overs         50 non-null float64
Player        50 non-null object
Runs          50 non-null int64
Wkts          50 non-null int64
Year          50 non-null int64
dtypes: float64(3), int64(5), object(3)
memory usage: 4.4+ KB

In [184]:
Ind_Bow_wkts_4years_home.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 11 columns):
Unnamed: 0    0 non-null float64
Econ          50 non-null float64
Ground        50 non-null object
Inns          50 non-null int64
Mdns          50 non-null int64
Opposition    50 non-null object
Overs         50 non-null float64
Player        50 non-null object
Runs          50 non-null int64
Wkts          50 non-null int64
Year          50 non-null int64
dtypes: float64(3), int64(5), object(3)
memory usage: 4.4+ KB

In [185]:
Ind_Aus_master_df = Ind_Aus_Bow_wkts_2years.append([Ind_Aus_Bow_wkts_2years_2,
Ind_Aus_Bow_wkts_2years_3, 
Ind_Aus_Bow_wkts_2years_4, 
Ind_Aus_Bow_wkts_2years_5, 
Ind_Aus_Bow_wkts_2years_6, 
Ind_Aus_Bow_wkts_2years_7, 
Ind_Aus_Bow_wkts_2years_8, 
Ind_Aus_Bow_wkts_2years_9, 
Ind_Bow_wkts_4years_home, 
Ind_Bow_wkts_4years_home_2, 
Ind_Bow_wkts_4years_home_3,
Ind_Bow_wkts_4years_home_4,  
Aus_India_Bow_wkts_10years_selected_venues,
Aus_India_Bow_wkts_10years_selected_venues_2,
Aus_India_Bow_wkts_10years_selected_venues_3,
Aus_India_Bow_wkts_10years_selected_venues_4
 ])

In [186]:
Ind_Aus_master_df.drop_duplicates( inplace=True)


Ind_Aus_master_df.drop(['Unnamed: 0', 'Econ', 'Inns','Mdns','Runs','Overs'], axis=1, inplace=True)
Ind_Aus_master_df.reset_index()

,index,Ground,Opposition,Player,Wkts,Year
0,0,Nottingham,v England,Kuldeep Yadav (INDIA),6,2018
1,1,Melbourne,v Australia,YS Chahal (INDIA),6,2019
2,2,Centurion,v South Africa,YS Chahal (INDIA),5,2018
3,3,Pallekele,v Sri Lanka,JJ Bumrah (INDIA),5,2017
4,4,Colombo (RPS),v Sri Lanka,B Kumar (INDIA),5,2017
5,5,Perth,v England,AJ Tye (AUS),5,2018
6,6,Cape Town,v South Africa,Kuldeep Yadav (INDIA),4,2018
7,7,Adelaide,v England,PJ Cummins (AUS),4,2018
8,8,Sydney,v India,JA Richardson (AUS),4,2019
9,9,Dubai (DSC),v Bangladesh,RA Jadeja (INDIA),4,2018
10,10,Thiruvananthapuram,v West Indies,RA Jadeja (INDIA),4,2018
11,11,Pune,v West Indies,JJ Bumrah (INDIA),4,2018
12,12,Napier,v New Zealand,Kuldeep Yadav (INDIA),4,2019
13,13,Pallekele,v Sri Lanka,JJ Bumrah (INDIA),4,2017
14,14,Adelaide,v Australia,B Kumar (INDIA),4,2019
15,15,Mount Maunganui,v New Zealand,Kuldeep Yadav (INDIA),4,2019
16,16,Cape Town,v South Africa,YS Chahal (INDIA),4,2018
17,17,Kingston,v West Indies,Mohammed Shami (INDIA),4,2017
18,18,Centurion,v South Africa,SN Thakur (INDIA),4,2018
19,19,Port Elizabeth,v South Africa,Kuldeep Yadav (INDIA),4,2018
20,20,Brisbane,v England,MA Starc (AUS),4,2018
21,21,Bengaluru,v Australia,UT Yadav (INDIA),4,2017
22,22,Kolkata,v Australia,B Kumar (INDIA),3,2017
23,23,Mumbai (BS),v West Indies,KK Ahmed (INDIA),3,2018
24,24,Dubai (DSC),v Pakistan,B Kumar (INDIA),3,2018
25,25,Perth,v South Africa,MP Stoinis (AUS),3,2018
26,26,Napier,v New Zealand,Mohammed Shami (INDIA),3,2019
27,27,Centurion,v South Africa,Kuldeep Yadav (INDIA),3,2018
28,28,Dubai (DSC),v Pakistan,KM Jadhav (INDIA),3,2018
29,29,North Sound,v West Indies,R Ashwin (INDIA),3,2017
...,...,...,...,...,...,...
806,20,Nagpur,v India,XJ Doherty (AUS),0,2013
807,21,Nagpur,v India,GJ Maxwell (AUS),0,2013
808,22,Delhi,v India,PM Siddle (AUS),0,2009
809,23,Mohali,v Australia,P Kumar (INDIA),0,2009
810,24,Mohali,v Australia,I Sharma (INDIA),0,2009
811,25,Nagpur,v Sri Lanka,RA Jadeja (INDIA),0,2009
812,26,Hyderabad (Deccan),v India,NM Hauritz (AUS),0,2009
813,27,Hyderabad (Deccan),v Australia,RA Jadeja (INDIA),0,2009
814,28,Mohali,v England,R Ashwin (INDIA),0,2011
815,29,Mohali,v India,XJ Doherty (AUS),0,2013
816,30,Delhi,v New Zealand,HH Pandya (INDIA),0,2016
817,31,Nagpur,v India,SR Watson (AUS),0,2009
818,32,Nagpur,v New Zealand,JJ Krejza (AUS),0,2011
819,33,Nagpur,v South Africa,Yuvraj Singh (INDIA),0,2011
820,34,Nagpur,v India,CJ McKay (AUS),0,2013
821,35,Nagpur,v Sri Lanka,P Kumar (INDIA),0,2009
822,36,Nagpur,v Australia,Kuldeep Yadav (INDIA),0,2017
823,37,Mohali,v New Zealand,AR Patel (INDIA),0,2016
824,38,Delhi,v Australia,A Nehra (INDIA),0,2009
825,39,Nagpur,v India,SR Watson (AUS),0,2013
826,40,Nagpur,v India,NM Hauritz (AUS),0,2009
827,41,Mohali,v England,Mohammed Shami (INDIA),0,2013
828,42,Mohali,v Australia,R Ashwin (INDIA),0,2013
829,43,Ranchi,v Sri Lanka,KV Sharma (INDIA),0,2014
830,44,Nagpur,v South Africa,A Nehra (INDIA),0,2011
831,45,Mohali,v England,UT Yadav (INDIA),0,2011
832,46,Hyderabad (Deccan),v Australia,MM Patel (INDIA),0,2009
833,47,Mohali,v India,MG Johnson (AUS),0,2009
834,48,Nagpur,v Australia,A Mishra (INDIA),0,2013
835,49,Nagpur,v India,TD Paine (AUS),-,2009

In [187]:
Ind_Aus_master_df_new =Ind_Aus_master_df.reset_index()

In [188]:

Ind_Aus_master_df_new.drop(['index'], axis=1, inplace=True)
Ind_Aus_master_df_new.columns

Index(['Ground', 'Opposition', 'Player', 'Wkts', 'Year'], dtype='object')

In [189]:
Ind_Aus_master_df_new.replace('-','0')

                 Ground      Opposition                  Player Wkts  Year
0            Nottingham       v England   Kuldeep Yadav (INDIA)    6  2018
1             Melbourne     v Australia       YS Chahal (INDIA)    6  2019
2             Centurion  v South Africa       YS Chahal (INDIA)    5  2018
3             Pallekele     v Sri Lanka       JJ Bumrah (INDIA)    5  2017
4         Colombo (RPS)     v Sri Lanka         B Kumar (INDIA)    5  2017
5                 Perth       v England            AJ Tye (AUS)    5  2018
6             Cape Town  v South Africa   Kuldeep Yadav (INDIA)    4  2018
7              Adelaide       v England        PJ Cummins (AUS)    4  2018
8                Sydney         v India     JA Richardson (AUS)    4  2019
9           Dubai (DSC)    v Bangladesh       RA Jadeja (INDIA)    4  2018
10   Thiruvananthapuram   v West Indies       RA Jadeja (INDIA)    4  2018
11                 Pune   v West Indies       JJ Bumrah (INDIA)    4  2018
12               Napier   v New Zealand   Kuldeep Yadav (INDIA)    4  2019
13            Pallekele     v Sri Lanka       JJ Bumrah (INDIA)    4  2017
14             Adelaide     v Australia         B Kumar (INDIA)    4  2019
15      Mount Maunganui   v New Zealand   Kuldeep Yadav (INDIA)    4  2019
16            Cape Town  v South Africa       YS Chahal (INDIA)    4  2018
17             Kingston   v West Indies  Mohammed Shami (INDIA)    4  2017
18            Centurion  v South Africa       SN Thakur (INDIA)    4  2018
19       Port Elizabeth  v South Africa   Kuldeep Yadav (INDIA)    4  2018
20             Brisbane       v England          MA Starc (AUS)    4  2018
21            Bengaluru     v Australia        UT Yadav (INDIA)    4  2017
22              Kolkata     v Australia         B Kumar (INDIA)    3  2017
23          Mumbai (BS)   v West Indies        KK Ahmed (INDIA)    3  2018
24          Dubai (DSC)      v Pakistan         B Kumar (INDIA)    3  2018
25                Perth  v South Africa        MP Stoinis (AUS)    3  2018
26               Napier   v New Zealand  Mohammed Shami (INDIA)    3  2019
27            Centurion  v South Africa   Kuldeep Yadav (INDIA)    3  2018
28          Dubai (DSC)      v Pakistan       KM Jadhav (INDIA)    3  2018
29          North Sound   v West Indies        R Ashwin (INDIA)    3  2017
..                  ...             ...                     ...  ...   ...
806              Nagpur         v India        XJ Doherty (AUS)    0  2013
807              Nagpur         v India        GJ Maxwell (AUS)    0  2013
808               Delhi         v India         PM Siddle (AUS)    0  2009
809              Mohali     v Australia         P Kumar (INDIA)    0  2009
810              Mohali     v Australia        I Sharma (INDIA)    0  2009
811              Nagpur     v Sri Lanka       RA Jadeja (INDIA)    0  2009
812  Hyderabad (Deccan)         v India        NM Hauritz (AUS)    0  2009
813  Hyderabad (Deccan)     v Australia       RA Jadeja (INDIA)    0  2009
814              Mohali       v England        R Ashwin (INDIA)    0  2011
815              Mohali         v India        XJ Doherty (AUS)    0  2013
816               Delhi   v New Zealand       HH Pandya (INDIA)    0  2016
817              Nagpur         v India         SR Watson (AUS)    0  2009
818              Nagpur   v New Zealand         JJ Krejza (AUS)    0  2011
819              Nagpur  v South Africa    Yuvraj Singh (INDIA)    0  2011
820              Nagpur         v India          CJ McKay (AUS)    0  2013
821              Nagpur     v Sri Lanka         P Kumar (INDIA)    0  2009
822              Nagpur     v Australia   Kuldeep Yadav (INDIA)    0  2017
823              Mohali   v New Zealand        AR Patel (INDIA)    0  2016
824               Delhi     v Australia         A Nehra (INDIA)    0  2009
825              Nagpur         v India         SR Watson (AUS)    0  2013
826              Nagpur         v India        NM Hauritz (AUS)    0  2009
827              Mohali       v England  Mohammed Shami (INDIA)    0  2013
828              Mohali     v Australia        R Ashwin (INDIA)    0  2013
829              Ranchi     v Sri Lanka       KV Sharma (INDIA)    0  2014
830              Nagpur  v South Africa         A Nehra (INDIA)    0  2011
831              Mohali       v England        UT Yadav (INDIA)    0  2011
832  Hyderabad (Deccan)     v Australia        MM Patel (INDIA)    0  2009
833              Mohali         v India        MG Johnson (AUS)    0  2009
834              Nagpur     v Australia        A Mishra (INDIA)    0  2013
835              Nagpur         v India          TD Paine (AUS)    0  2009

[836 rows x 5 columns]

In [190]:
Ind_Aus_master_df_new['Player']  = Ind_Aus_master_df_new['Player'].str.split().str.get(0)+Ind_Aus_master_df_new['Player'].str.split().str.get(1)
Ind_Aus_master_df_new.Player.unique()

array(['KuldeepYadav', 'YSChahal', 'JJBumrah', 'BKumar', 'AJTye',
       'PJCummins', 'JARichardson', 'RAJadeja', 'MohammedShami',
       'SNThakur', 'MAStarc', 'UTYadav', 'KKAhmed', 'MPStoinis',
       'KMJadhav', 'RAshwin', 'ARPatel', 'BStanlake', 'JRHazlewood',
       'HHPandya', 'NMCoulter-Nile', 'KWRichardson', 'MRMarsh',
       'JPBehrendorff', 'MGNeser', 'ACAgar', 'AZampa', 'GJMaxwell',
       'DLChahar', 'NMLyon', 'PMSiddle', 'WashingtonSundar', 'JPFaulkner',
       'ATRayudu', 'AJFinch', 'SSIyer', 'MCHenriques', 'TMHead',
       'SKRaina', 'VKohli', 'DJMShort', 'VShankar', 'YuvrajSingh',
       'SKaul', 'MohammedSiraj', 'MSDhoni', 'SDhawan', 'RGSharma',
       'DAWarner', 'MSWade', 'SPDSmith', 'AMishra', 'HarbhajanSingh',
       'MMSharma', 'JYadav', 'DSKulkarni', 'STRBinny', 'AMRahane',
       'MKPandey', 'RVinay', 'MGJohnson', 'ZKhan', 'SRWatson', 'SWTait',
       'ISharma', 'ANehra', 'DEBollinger', 'CJMcKay', 'NMHauritz',
       'PKumar', 'MMPatel', 'PPChawla', 'BLee', 'BWHilfenhaus', 'ACVoges',
       'YKPathan', 'MEKHussey', 'XJDoherty', 'JJKrejza', 'KVSharma',
       'TDPaine'], dtype=object)

In [191]:
current_Player_list =['KuldeepYadav', 'YSChahal', 'JJBumrah', 'BKumar', 
       'PJCummins', 'JARichardson', 'RAJadeja', 'MohammedShami',
        'UTYadav', 'MPStoinis',
       'KMJadhav',  
       'NMCoulter-Nile', 'KWRichardson', 
       'JPBehrendorff',  'AZampa', 'GJMaxwell',
        'NMLyon', 'VShankar', 
       'SKaul']

In [192]:
Ind_Aus_master_df_new = Ind_Aus_master_df_new[Ind_Aus_master_df_new['Player'].isin(current_Player_list)]

In [193]:
Ind_Aus_master_df_filtered = Ind_Aus_master_df_new.reset_index()

In [194]:

Ind_Aus_master_df_filtered.replace('-','0')
Ind_Aus_master_df_filtered['Wkts']
#Ind_Aus_master_df_filtered = Ind_Aus_master_df_filtered[0:888]
#Ind_Aus_master_df_filtered

0      6
1      6
2      5
3      5
4      5
5      4
6      4
7      4
8      4
9      4
10     4
11     4
12     4
13     4
14     4
15     4
16     4
17     4
18     4
19     3
20     3
21     3
22     3
23     3
24     3
25     3
26     3
27     3
28     3
29     3
      ..
406    2
407    2
408    2
409    1
410    1
411    1
412    1
413    1
414    1
415    1
416    1
417    1
418    1
419    1
420    1
421    1
422    1
423    1
424    0
425    0
426    0
427    0
428    0
429    0
430    0
431    0
432    0
433    0
434    0
435    0
Name: Wkts, Length: 436, dtype: object

In [195]:
testCases_wkts_hyd = pd.read_csv("C:\\Users\\sushanth\\Desktop\\testCases_wkts_hyd_new.csv", sep=",", header = 0, engine='python', encoding ="utf-8", skipinitialspace=True)
testCases_wkts_ranchi = pd.read_csv("C:\\Users\\sushanth\\Desktop\\testCases_wkts_ranchi_new.csv", sep=",", header = 0, engine='python', encoding ="utf-8", skipinitialspace=True)
testCases_wkts_delhi = pd.read_csv("C:\\Users\\sushanth\\Desktop\\testCases_wkts_delhi_new.csv", sep=",", header = 0, engine='python', encoding ="utf-8", skipinitialspace=True)
testCases_wkts_nagpur = pd.read_csv("C:\\Users\\sushanth\\Desktop\\testCases_wkts_nagpur_new.csv", sep=",", header = 0, engine='python', encoding ="utf-8", skipinitialspace=True)
testCases_wkts_mohali = pd.read_csv("C:\\Users\\sushanth\\Desktop\\testCases_wkts_mohali_new.csv", sep=",", header = 0, engine='python', encoding ="utf-8", skipinitialspace=True)
testCases_wkts_hyd.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19 entries, 0 to 18
Data columns (total 4 columns):
Ground        19 non-null object
Opposition    19 non-null object
Player        19 non-null object
Year          19 non-null int64
dtypes: int64(1), object(3)
memory usage: 688.0+ bytes

In [196]:

Ind_Aus_master_df_filtered = Ind_Aus_master_df_filtered.append([testCases_wkts_hyd,testCases_wkts_ranchi,testCases_wkts_delhi,testCases_wkts_nagpur,testCases_wkts_mohali])
Ind_Aus_master_df_filtered.reset_index()

,level_0,Ground,Opposition,Player,Wkts,Year,index
0,0,Nottingham,v England,KuldeepYadav,6,2018,0.0
1,1,Melbourne,v Australia,YSChahal,6,2019,1.0
2,2,Centurion,v South Africa,YSChahal,5,2018,2.0
3,3,Pallekele,v Sri Lanka,JJBumrah,5,2017,3.0
4,4,Colombo (RPS),v Sri Lanka,BKumar,5,2017,4.0
5,5,Cape Town,v South Africa,KuldeepYadav,4,2018,6.0
6,6,Adelaide,v England,PJCummins,4,2018,7.0
7,7,Sydney,v India,JARichardson,4,2019,8.0
8,8,Dubai (DSC),v Bangladesh,RAJadeja,4,2018,9.0
9,9,Thiruvananthapuram,v West Indies,RAJadeja,4,2018,10.0
10,10,Pune,v West Indies,JJBumrah,4,2018,11.0
11,11,Napier,v New Zealand,KuldeepYadav,4,2019,12.0
12,12,Pallekele,v Sri Lanka,JJBumrah,4,2017,13.0
13,13,Adelaide,v Australia,BKumar,4,2019,14.0
14,14,Mount Maunganui,v New Zealand,KuldeepYadav,4,2019,15.0
15,15,Cape Town,v South Africa,YSChahal,4,2018,16.0
16,16,Kingston,v West Indies,MohammedShami,4,2017,17.0
17,17,Port Elizabeth,v South Africa,KuldeepYadav,4,2018,19.0
18,18,Bengaluru,v Australia,UTYadav,4,2017,21.0
19,19,Kolkata,v Australia,BKumar,3,2017,22.0
20,20,Dubai (DSC),v Pakistan,BKumar,3,2018,24.0
21,21,Perth,v South Africa,MPStoinis,3,2018,25.0
22,22,Napier,v New Zealand,MohammedShami,3,2019,26.0
23,23,Centurion,v South Africa,KuldeepYadav,3,2018,27.0
24,24,Dubai (DSC),v Pakistan,KMJadhav,3,2018,28.0
25,25,Birmingham,v Pakistan,UTYadav,3,2017,30.0
26,26,Chennai,v Australia,YSChahal,3,2017,31.0
27,27,Dubai (DSC),v Bangladesh,BKumar,3,2018,32.0
28,28,Durban,v South Africa,KuldeepYadav,3,2018,35.0
29,29,Adelaide,v South Africa,MPStoinis,3,2018,37.0
...,...,...,...,...,...,...,...
501,8,Nagpur,v Australia,VShankar,NaN,2019,NaN
502,9,Nagpur,v Australia,SKaul,NaN,2019,NaN
503,10,Nagpur,v India,PJCummins,NaN,2019,NaN
504,11,Nagpur,v India,JARichardson,NaN,2019,NaN
505,12,Nagpur,v India,MPStoinis,NaN,2019,NaN
506,13,Nagpur,v India,NMCoulter-Nile,NaN,2019,NaN
507,14,Nagpur,v India,KWRichardson,NaN,2019,NaN
508,15,Nagpur,v India,GJMaxwell,NaN,2019,NaN
509,16,Nagpur,v India,JPBehrendorff,NaN,2019,NaN
510,17,Nagpur,v India,AZampa,NaN,2019,NaN
511,18,Nagpur,v India,NMLyon,NaN,2019,NaN
512,0,Mohali,v Australia,KuldeepYadav,NaN,2019,NaN
513,1,Mohali,v Australia,YSChahal,NaN,2019,NaN
514,2,Mohali,v Australia,JJBumrah,NaN,2019,NaN
515,3,Mohali,v Australia,BKumar,NaN,2019,NaN
516,4,Mohali,v Australia,RAJadeja,NaN,2019,NaN
517,5,Mohali,v Australia,MohammedShami,NaN,2019,NaN
518,6,Mohali,v Australia,UTYadav,NaN,2019,NaN
519,7,Mohali,v Australia,KMJadhav,NaN,2019,NaN
520,8,Mohali,v Australia,VShankar,NaN,2019,NaN
521,9,Mohali,v Australia,SKaul,NaN,2019,NaN
522,10,Mohali,v India,PJCummins,NaN,2019,NaN
523,11,Mohali,v India,JARichardson,NaN,2019,NaN
524,12,Mohali,v India,MPStoinis,NaN,2019,NaN
525,13,Mohali,v India,NMCoulter-Nile,NaN,2019,NaN
526,14,Mohali,v India,KWRichardson,NaN,2019,NaN
527,15,Mohali,v India,GJMaxwell,NaN,2019,NaN
528,16,Mohali,v India,JPBehrendorff,NaN,2019,NaN
529,17,Mohali,v India,AZampa,NaN,2019,NaN
530,18,Mohali,v India,NMLyon,NaN,2019,NaN

In [197]:
Ind_Aus_master_df_filtered_Opposition = pd.get_dummies(Ind_Aus_master_df_filtered['Opposition'],prefix="Opposition")
#Adding the results to the master dataframe
Ind_Aus_master_df_filtered = pd.concat([Ind_Aus_master_df_filtered,Ind_Aus_master_df_filtered_Opposition],axis=1)
Ind_Aus_master_df_filtered.drop(['Opposition'],axis=1,inplace=True)



Ind_Aus_master_df_filtered_Ground = pd.get_dummies(Ind_Aus_master_df_filtered['Ground'],prefix="Ground")
#Adding the results to the master dataframe
Ind_Aus_master_df_filtered = pd.concat([Ind_Aus_master_df_filtered,Ind_Aus_master_df_filtered_Ground],axis=1)
Ind_Aus_master_df_filtered.drop(['Ground'],axis=1,inplace=True)



Ind_Aus_master_df_filtered_Year = pd.get_dummies(Ind_Aus_master_df_filtered['Year'],prefix="Year")
#Adding the results to the master dataframe
Ind_Aus_master_df_filtered = pd.concat([Ind_Aus_master_df_filtered,Ind_Aus_master_df_filtered_Year],axis=1)
Ind_Aus_master_df_filtered.drop(['Year'],axis=1,inplace=True)

Ind_Aus_master_df_filtered_Player = pd.get_dummies(Ind_Aus_master_df_filtered['Player'],prefix="Player")
#Adding the results to the master dataframe
Ind_Aus_master_df_filtered = pd.concat([Ind_Aus_master_df_filtered,Ind_Aus_master_df_filtered_Player],axis=1)
Ind_Aus_master_df_filtered.drop(['Player'],axis=1,inplace=True)

In [198]:
Ind_Aus_master_df_filtered

,Wkts,index,Opposition_v Afghanistan,Opposition_v Australia,Opposition_v Bangladesh,Opposition_v England,Opposition_v Hong Kong,Opposition_v India,Opposition_v New Zealand,Opposition_v Pakistan,...,Player_MPStoinis,Player_MohammedShami,Player_NMCoulter-Nile,Player_NMLyon,Player_PJCummins,Player_RAJadeja,Player_SKaul,Player_UTYadav,Player_VShankar,Player_YSChahal
0,6,0.0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,6,1.0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
2,5,2.0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
3,5,3.0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,5,4.0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5,4,6.0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
6,4,7.0,0,0,0,1,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
7,4,8.0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
8,4,9.0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
9,4,10.0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
10,4,11.0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
11,4,12.0,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
12,4,13.0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
13,4,14.0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
14,4,15.0,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
15,4,16.0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
16,4,17.0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
17,4,19.0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
18,4,21.0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
19,3,22.0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
20,3,24.0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
21,3,25.0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
22,3,26.0,0,0,0,0,0,0,1,0,...,0,1,0,0,0,0,0,0,0,0
23,3,27.0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
24,3,28.0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
25,3,30.0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,1,0,0
26,3,31.0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
27,3,32.0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
28,3,35.0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
29,3,37.0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8,NaN,NaN,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
9,NaN,NaN,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
10,NaN,NaN,0,0,0,0,0,1,0,0,...,0,0,0,0,1,0,0,0,0,0
11,NaN,NaN,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
12,NaN,NaN,0,0,0,0,0,1,0,0,...,1,0,0,0,0,0,0,0,0,0
13,NaN,NaN,0,0,0,0,0,1,0,0,...,0,0,1,0,0,0,0,0,0,0
14,NaN,NaN,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
15,NaN,NaN,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
16,NaN,NaN,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
17,NaN,NaN,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
18,NaN,NaN,0,0,0,0,0,1,0,0,...,0,0,0,1,0,0,0,0,0,0
0,NaN,NaN,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,NaN,NaN,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
2,NaN,NaN,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,NaN,NaN,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,NaN,NaN,0,1,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
5,NaN,NaN,0,1,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
6,NaN,NaN,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
7,NaN,NaN,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
8,NaN,NaN,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
9,NaN,NaN,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
10,NaN,NaN,0,0,0,0,0,1,0,0,...,0,0,0,0,1,0,0,0,0,0
11,NaN,NaN,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
12,NaN,NaN,0,0,0,0,0,1,0,0,...,1,0,0,0,0,0,0,0,0,0
13,NaN,NaN,0,0,0,0,0,1,0,0,...,0,0,1,0,0,0,0,0,0,0
14,NaN,NaN,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
15,NaN,NaN,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
16,NaN,NaN,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
17,NaN,NaN,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
18,NaN,NaN,0,0,0,0,0,1,0,0,...,0,0,0,1,0,0,0,0,0,0

In [199]:
# Putting feature variable to X
# Putting feature variable to X
Ind_Aus_master_df_filtered_new = Ind_Aus_master_df_filtered.reset_index()
Ind_Aus_master_df_filtered_new.drop(['index'], axis=1, inplace=True)
Ind_Aus_master_df_filtered_new["Wkts"]= Ind_Aus_master_df_filtered_new["Wkts"].replace('-', '0') 
Ind_Aus_master_df_filtered_new['Wkts'].fillna('0', inplace=True)

#Ind_Aus_master_df_filtered_new['Runs'] = Ind_Aus_master_df_filtered_new['Runs'].astype(int)
X_train = Ind_Aus_master_df_filtered_new[0:436].drop(['Wkts'],axis=1)

# Putting response variable to y
y_train = Ind_Aus_master_df_filtered_new[0:436]['Wkts']

X_test_hyd = Ind_Aus_master_df_filtered_new[436:455].drop(['Wkts'],axis=1)

# Putting response variable to y
y_test_hyd = Ind_Aus_master_df_filtered_new[436:455]['Wkts']

X_test_ranchi = Ind_Aus_master_df_filtered_new[455:474].drop(['Wkts'],axis=1)

# Putting response variable to y
y_test_ranchi = Ind_Aus_master_df_filtered_new[455:474]['Wkts']

X_test_delhi = Ind_Aus_master_df_filtered_new[474:493].drop(['Wkts'],axis=1)

# Putting response variable to y
y_test_delhi = Ind_Aus_master_df_filtered_new[474:493]['Wkts']

X_test_nagpur = Ind_Aus_master_df_filtered_new[493:512].drop(['Wkts'],axis=1)

# Putting response variable to y
y_test_nagpur = Ind_Aus_master_df_filtered_new[493:512]['Wkts']

X_test_mohali = Ind_Aus_master_df_filtered_new[512:].drop(['Wkts'],axis=1)

# Putting response variable to y
y_test_mohali= Ind_Aus_master_df_filtered_new[512:]['Wkts']



y_train

0      6
1      6
2      5
3      5
4      5
5      4
6      4
7      4
8      4
9      4
10     4
11     4
12     4
13     4
14     4
15     4
16     4
17     4
18     4
19     3
20     3
21     3
22     3
23     3
24     3
25     3
26     3
27     3
28     3
29     3
      ..
406    2
407    2
408    2
409    1
410    1
411    1
412    1
413    1
414    1
415    1
416    1
417    1
418    1
419    1
420    1
421    1
422    1
423    1
424    0
425    0
426    0
427    0
428    0
429    0
430    0
431    0
432    0
433    0
434    0
435    0
Name: Wkts, Length: 436, dtype: object

In [200]:
from sklearn.linear_model import LinearRegression
# Representing LinearRegression as lr(Creating LinearRegression Object)
lm = LinearRegression()
# fit the model to the training data
lm.fit(X_train,y_train)
# Making predictions using the model
y_pred_hyd = lm.predict(X_test_hyd)
y_pred_ranchi = lm.predict(X_test_ranchi)
y_pred_delhi = lm.predict(X_test_delhi)
y_pred_nagpur = lm.predict(X_test_nagpur)
y_pred_mohali = lm.predict(X_test_mohali)

In [201]:
y_pred_overall =[a+b+c+d+e for a,b,c,d,e in zip(y_pred_hyd, y_pred_ranchi,y_pred_delhi,y_pred_nagpur,y_pred_mohali)]
y_pred_overall

[21.92627414675845,
 20.916237668913585,
 20.270312086752526,
 18.996731986231932,
 20.57569969583541,
 19.59001349750866,
 19.900255250049945,
 16.96848869385278,
 14.358161262098033,
 16.477681057675,
 16.010074527488626,
 19.05331973686871,
 15.971362951080165,
 16.657781413489328,
 18.143057764297815,
 13.368483870517586,
 17.128384179611643,
 14.905226457255601,
 15.089174130352626]

## 1st player in the list i.e Kuldeep Yadav will take the maximum number of wickets in the series