In [79]:
import numpy as np
import pandas as pd 
import matplotlib.pyplot as plt
import seaborn as sns
from matplotlib import cm
from IPython.display import display,HTML
from datetime import datetime
from dateutil.parser import parse
# reading data files
Ind_Aus_Bat_runs_2years = pd.read_csv("C:\\Users\\sushanth\\Desktop\\Ind_Aus_Bat_runs_2years.csv", sep=",", header = 0, engine='python', encoding ="utf-8", skipinitialspace=True)
Ind_Aus_Bat_runs_2years_2 = pd.read_csv("C:\\Users\\sushanth\\Desktop\\Ind_Aus_Bat_runs_2years_2.csv", sep=",", header = 0, engine='python', encoding ="utf-8", skipinitialspace=True)
Ind_Aus_Bat_runs_2years_3 = pd.read_csv("C:\\Users\\sushanth\\Desktop\\Ind_Aus_Bat_runs_2years_3.csv", sep=",", header = 0, engine='python', encoding ="utf-8", skipinitialspace=True)
Ind_Aus_Bat_runs_2years_4 = pd.read_csv("C:\\Users\\sushanth\\Desktop\\Ind_Aus_Bat_runs_2years_4.csv", sep=",", header = 0, engine='python', encoding ="utf-8", skipinitialspace=True)
Ind_Aus_Bat_runs_2years_5 = pd.read_csv("C:\\Users\\sushanth\\Desktop\\Ind_Aus_Bat_runs_2years_5.csv", sep=",", header = 0, engine='python', encoding ="utf-8", skipinitialspace=True)
Ind_Aus_Bat_runs_2years_6 = pd.read_csv("C:\\Users\\sushanth\\Desktop\\Ind_Aus_Bat_runs_2years_6.csv", sep=",", header = 0, engine='python', encoding ="utf-8", skipinitialspace=True)
Ind_Aus_Bat_runs_2years_7 = pd.read_csv("C:\\Users\\sushanth\\Desktop\\Ind_Aus_Bat_runs_2years_7.csv", sep=",", header = 0, engine='python', encoding ="utf-8", skipinitialspace=True)
Ind_Aus_Bat_runs_2years_8 = pd.read_csv("C:\\Users\\sushanth\\Desktop\\Ind_Aus_Bat_runs_2years_8.csv", sep=",", header = 0, engine='python', encoding ="utf-8", skipinitialspace=True)
Ind_Aus_Bat_runs_2years_9 = pd.read_csv("C:\\Users\\sushanth\\Desktop\\Ind_Aus_Bat_runs_2years_9.csv", sep=",", header = 0, engine='python', encoding ="utf-8", skipinitialspace=True)
Ind_Aus_Bat_runs_2years_10 = pd.read_csv("C:\\Users\\sushanth\\Desktop\\Ind_Aus_Bat_runs_2years_10.csv", sep=",", header = 0, engine='python', encoding ="utf-8", skipinitialspace=True)
Ind_Aus_Bat_runs_2years_11 = pd.read_csv("C:\\Users\\sushanth\\Desktop\\Ind_Aus_Bat_runs_2years_11.csv", sep=",", header = 0, engine='python', encoding ="utf-8", skipinitialspace=True)
Ind_Aus_Bat_runs_2years_12 = pd.read_csv("C:\\Users\\sushanth\\Desktop\\Ind_Aus_Bat_runs_2years_12.csv", sep=",", header = 0, engine='python', encoding ="utf-8", skipinitialspace=True)
Ind_Aus_Bat_runs_2years_13 = pd.read_csv("C:\\Users\\sushanth\\Desktop\\Ind_Aus_Bat_runs_2years_13.csv", sep=",", header = 0, engine='python', encoding ="utf-8", skipinitialspace=True)
Ind_Aus_Bat_runs_2years_14 = pd.read_csv("C:\\Users\\sushanth\\Desktop\\Ind_Aus_Bat_runs_2years_14.csv", sep=",", header = 0, engine='python', encoding ="utf-8", skipinitialspace=True)
Ind_Aus_Bat_runs_2years_15 = pd.read_csv("C:\\Users\\sushanth\\Desktop\\Ind_Aus_Bat_runs_2years_15.csv", sep=",", header = 0, engine='python', encoding ="utf-8", skipinitialspace=True)
Ind_Aus_Bat_runs_2years_16 = pd.read_csv("C:\\Users\\sushanth\\Desktop\\Ind_Aus_Bat_runs_2years_16.csv", sep=",", header = 0, engine='python', encoding ="utf-8", skipinitialspace=True)
Ind_Aus_Bat_runs_2years_17 = pd.read_csv("C:\\Users\\sushanth\\Desktop\\Ind_Aus_Bat_runs_2years_17.csv", sep=",", header = 0, engine='python', encoding ="utf-8", skipinitialspace=True)

Ind_Bat_runs_4years_home = pd.read_csv("C:\\Users\\sushanth\\Desktop\\Ind_Bat_runs_4years_home.csv", sep=",", header = 0, engine='python', encoding ="utf-8", skipinitialspace=True)
Ind_Bat_runs_4years_home_2 = pd.read_csv("C:\\Users\\sushanth\\Desktop\\Ind_Bat_runs_4years_home_2.csv", sep=",", header = 0, engine='python', encoding ="utf-8", skipinitialspace=True)
Ind_Bat_runs_4years_home_3 = pd.read_csv("C:\\Users\\sushanth\\Desktop\\Ind_Bat_runs_4years_home_3.csv", sep=",", header = 0, engine='python', encoding ="utf-8", skipinitialspace=True)
Ind_Bat_runs_4years_home_4 = pd.read_csv("C:\\Users\\sushanth\\Desktop\\Ind_Bat_runs_4years_home_4.csv", sep=",", header = 0, engine='python', encoding ="utf-8", skipinitialspace=True)
Ind_Bat_runs_4years_home_5 = pd.read_csv("C:\\Users\\sushanth\\Desktop\\Ind_Bat_runs_4years_home_5.csv", sep=",", header = 0, engine='python', encoding ="utf-8", skipinitialspace=True)
Ind_Bat_runs_4years_home_6 = pd.read_csv("C:\\Users\\sushanth\\Desktop\\Ind_Bat_runs_4years_home_6.csv", sep=",", header = 0, engine='python', encoding ="utf-8", skipinitialspace=True)
Ind_Bat_runs_4years_home_7 = pd.read_csv("C:\\Users\\sushanth\\Desktop\\Ind_Bat_runs_4years_home_7.csv", sep=",", header = 0, engine='python', encoding ="utf-8", skipinitialspace=True)


Ind_Aus_Bat_runs_10years_home = pd.read_csv("C:\\Users\\sushanth\\Desktop\\Ind_Aus_Bat_runs_10years_home.csv", sep=",", header = 0, engine='python', encoding ="utf-8", skipinitialspace=True)
Ind_Aus_Bat_runs_10years_home_2 = pd.read_csv("C:\\Users\\sushanth\\Desktop\\Ind_Aus_Bat_runs_10years_home_2.csv", sep=",", header = 0, engine='python', encoding ="utf-8", skipinitialspace=True)
Ind_Aus_Bat_runs_10years_home_3 = pd.read_csv("C:\\Users\\sushanth\\Desktop\\Ind_Aus_Bat_runs_10years_home_3.csv", sep=",", header = 0, engine='python', encoding ="utf-8", skipinitialspace=True)
#Ind_Aus_Bat_runs_10years_home_4 = pd.read_csv("C:\\Users\\sushanth\\Desktop\\Ind_Aus_Bat_runs_10years_home_4.csv", sep=",", header = 0, engine='python', encoding ="utf-8", skipinitialspace=True)

Aus_India_Bat_runs_10years_away = pd.read_csv("C:\\Users\\sushanth\\Desktop\\Aus_India_Bat_runs_10years_away.csv", sep=",", header = 0, engine='python', encoding ="utf-8", skipinitialspace=True)
Aus_India_Bat_runs_10years_away_2 = pd.read_csv("C:\\Users\\sushanth\\Desktop\\Aus_India_Bat_runs_10years_away_2.csv", sep=",", header = 0, engine='python', encoding ="utf-8", skipinitialspace=True)
Aus_India_Bat_runs_10years_away_3 = pd.read_csv("C:\\Users\\sushanth\\Desktop\\Aus_India_Bat_runs_10years_away_3.csv", sep=",", header = 0, engine='python', encoding ="utf-8", skipinitialspace=True)
Aus_India_Bat_runs_10years_away_4 = pd.read_csv("C:\\Users\\sushanth\\Desktop\\Aus_India_Bat_runs_10years_away_4.csv", sep=",", header = 0, engine='python', encoding ="utf-8", skipinitialspace=True)

Aus_India_Bat_runs_10years_selected_venues = pd.read_csv("C:\\Users\\sushanth\\Desktop\\Aus_India_Bat_runs_10years_selected_venues.csv", sep=",", header = 0, engine='python', encoding ="utf-8", skipinitialspace=True)
Aus_India_Bat_runs_10years_selected_venues_2 = pd.read_csv("C:\\Users\\sushanth\\Desktop\\Aus_India_Bat_runs_10years_selected_venues_2.csv", sep=",", header = 0, engine='python', encoding ="utf-8", skipinitialspace=True)
Aus_India_Bat_runs_10years_selected_venues_3 = pd.read_csv("C:\\Users\\sushanth\\Desktop\\Aus_India_Bat_runs_10years_selected_venues_3.csv", sep=",", header = 0, engine='python', encoding ="utf-8", skipinitialspace=True)
Aus_India_Bat_runs_10years_selected_venues_4 = pd.read_csv("C:\\Users\\sushanth\\Desktop\\Aus_India_Bat_runs_10years_selected_venues_4.csv", sep=",", header = 0, engine='python', encoding ="utf-8", skipinitialspace=True)
Aus_India_Bat_runs_10years_selected_venues_5 = pd.read_csv("C:\\Users\\sushanth\\Desktop\\Aus_India_Bat_runs_10years_selected_venues_5.csv", sep=",", header = 0, engine='python', encoding ="utf-8", skipinitialspace=True)
Aus_India_Bat_runs_10years_selected_venues_6 = pd.read_csv("C:\\Users\\sushanth\\Desktop\\Aus_India_Bat_runs_10years_selected_venues_6.csv", sep=",", header = 0, engine='python', encoding ="utf-8", skipinitialspace=True)

Aus_Bat_runs_4years_away = pd.read_csv("C:\\Users\\sushanth\\Desktop\\Aus_Bat_runs_4years_away.csv", sep=",", header = 0, engine='python', encoding ="utf-8", skipinitialspace=True)
Aus_Bat_runs_4years_away_2 = pd.read_csv("C:\\Users\\sushanth\\Desktop\\Aus_Bat_runs_4years_away_2.csv", sep=",", header = 0, engine='python', encoding ="utf-8", skipinitialspace=True)
Aus_Bat_runs_4years_away_3 = pd.read_csv("C:\\Users\\sushanth\\Desktop\\Aus_Bat_runs_4years_away_3.csv", sep=",", header = 0, engine='python', encoding ="utf-8", skipinitialspace=True)
Aus_Bat_runs_4years_away_4 = pd.read_csv("C:\\Users\\sushanth\\Desktop\\Aus_Bat_runs_4years_away_4.csv", sep=",", header = 0, engine='python', encoding ="utf-8", skipinitialspace=True)
Aus_Bat_runs_4years_away_5 = pd.read_csv("C:\\Users\\sushanth\\Desktop\\Aus_Bat_runs_4years_away_5.csv", sep=",", header = 0, engine='python', encoding ="utf-8", skipinitialspace=True)
Aus_Bat_runs_4years_away_6 = pd.read_csv("C:\\Users\\sushanth\\Desktop\\Aus_Bat_runs_4years_away_6.csv", sep=",", header = 0, engine='python', encoding ="utf-8", skipinitialspace=True)
Aus_Bat_runs_4years_away_7 = pd.read_csv("C:\\Users\\sushanth\\Desktop\\Aus_Bat_runs_4years_away_7.csv", sep=",", header = 0, engine='python', encoding ="utf-8", skipinitialspace=True)
Aus_Bat_runs_4years_away_8 = pd.read_csv("C:\\Users\\sushanth\\Desktop\\Aus_Bat_runs_4years_away_8.csv", sep=",", header = 0, engine='python', encoding ="utf-8", skipinitialspace=True)
#testCases = pd.read_csv("C:\\Users\\sushanth\\Desktop\\testCases.csv", sep=",", header = 0, engine='python', encoding ="utf-8", skipinitialspace=True)

In [80]:
Ind_Aus_Bat_runs_2years.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 12 columns):
Unnamed: 0    0 non-null float64
4s            50 non-null int64
6s            50 non-null int64
BF            50 non-null int64
Ground        50 non-null object
Inns          50 non-null int64
Mins          50 non-null object
Opposition    50 non-null object
Player        50 non-null object
Runs          50 non-null object
SR            50 non-null float64
Year          50 non-null int64
dtypes: float64(2), int64(5), object(5)
memory usage: 4.8+ KB

In [81]:
Ind_Bat_runs_4years_home.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 12 columns):
Unnamed: 0    0 non-null float64
4s            50 non-null int64
6s            50 non-null int64
BF            50 non-null int64
Ground        50 non-null object
Inns          50 non-null int64
Mins          50 non-null object
Opposition    50 non-null object
Player        50 non-null object
Runs          50 non-null object
SR            50 non-null float64
Year          50 non-null int64
dtypes: float64(2), int64(5), object(5)
memory usage: 4.8+ KB

In [82]:
Ind_Aus_Bat_runs_10years_home.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 12 columns):
Unnamed: 0    0 non-null float64
4s            50 non-null int64
6s            50 non-null int64
BF            50 non-null int64
Ground        50 non-null object
Inns          50 non-null int64
Mins          50 non-null int64
Opposition    50 non-null object
Player        50 non-null object
Runs          50 non-null object
SR            50 non-null float64
Year          50 non-null int64
dtypes: float64(2), int64(6), object(4)
memory usage: 4.8+ KB

In [83]:
Aus_India_Bat_runs_10years_away.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 12 columns):
Unnamed: 0    0 non-null float64
4s            50 non-null int64
6s            50 non-null int64
BF            50 non-null int64
Ground        50 non-null object
Inns          50 non-null int64
Mins          50 non-null int64
Opposition    50 non-null object
Player        50 non-null object
Runs          50 non-null object
SR            50 non-null float64
Year          50 non-null int64
dtypes: float64(2), int64(6), object(4)
memory usage: 4.8+ KB

In [84]:
Aus_India_Bat_runs_10years_selected_venues.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 12 columns):
Unnamed: 0    0 non-null float64
4s            50 non-null int64
6s            50 non-null int64
BF            50 non-null int64
Ground        50 non-null object
Inns          50 non-null int64
Mins          50 non-null object
Opposition    50 non-null object
Player        50 non-null object
Runs          50 non-null object
SR            50 non-null float64
Year          50 non-null int64
dtypes: float64(2), int64(5), object(5)
memory usage: 4.8+ KB

In [85]:
Aus_Bat_runs_4years_away.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 12 columns):
Unnamed: 0    0 non-null float64
4s            50 non-null int64
6s            50 non-null int64
BF            50 non-null int64
Ground        50 non-null object
Inns          50 non-null int64
Mins          50 non-null object
Opposition    50 non-null object
Player        50 non-null object
Runs          50 non-null object
SR            50 non-null float64
Year          50 non-null int64
dtypes: float64(2), int64(5), object(5)
memory usage: 4.8+ KB

In [86]:
Ind_Aus_master_df = Ind_Aus_Bat_runs_2years.append([Ind_Aus_Bat_runs_2years_2,
Ind_Aus_Bat_runs_2years_3, 
Ind_Aus_Bat_runs_2years_4, 
Ind_Aus_Bat_runs_2years_5, 
Ind_Aus_Bat_runs_2years_6, 
Ind_Aus_Bat_runs_2years_7, 
Ind_Aus_Bat_runs_2years_8, 
Ind_Aus_Bat_runs_2years_9, 
Ind_Aus_Bat_runs_2years_10, 
Ind_Aus_Bat_runs_2years_11, 
Ind_Aus_Bat_runs_2years_12, 
Ind_Aus_Bat_runs_2years_13, 
Ind_Aus_Bat_runs_2years_14, 
Ind_Aus_Bat_runs_2years_15, 
Ind_Aus_Bat_runs_2years_16,  
Ind_Aus_Bat_runs_2years_17,
Ind_Bat_runs_4years_home, 
Ind_Bat_runs_4years_home_2, 
Ind_Bat_runs_4years_home_3,
Ind_Bat_runs_4years_home_4, 
Ind_Bat_runs_4years_home_5, 
Ind_Bat_runs_4years_home_6, 
Ind_Bat_runs_4years_home_7, 
Ind_Aus_Bat_runs_10years_home,
Ind_Aus_Bat_runs_10years_home_2,
Ind_Aus_Bat_runs_10years_home_3, 
Aus_India_Bat_runs_10years_away, 
Aus_India_Bat_runs_10years_away_2, 
Aus_India_Bat_runs_10years_away_3, 
Aus_India_Bat_runs_10years_away_4, 
Aus_India_Bat_runs_10years_selected_venues,
Aus_India_Bat_runs_10years_selected_venues_2,
Aus_India_Bat_runs_10years_selected_venues_3, 
Aus_India_Bat_runs_10years_selected_venues_4,
Aus_India_Bat_runs_10years_selected_venues_5,
Aus_India_Bat_runs_10years_selected_venues_6,  
Aus_Bat_runs_4years_away, 
Aus_Bat_runs_4years_away_2, 
Aus_Bat_runs_4years_away_3, 
Aus_Bat_runs_4years_away_4,
Aus_Bat_runs_4years_away_5, 
Aus_Bat_runs_4years_away_6,
Aus_Bat_runs_4years_away_7,
Aus_Bat_runs_4years_away_8 ])

In [87]:
Ind_Aus_master_df.drop_duplicates( inplace=True)


Ind_Aus_master_df.drop(['Unnamed: 0', 'BF', 'Inns','Mins','SR'], axis=1, inplace=True)
Ind_Aus_master_df.reset_index()

,index,4s,6s,Ground,Opposition,Player,Runs,Year
0,0,13,12,Mohali,v Sri Lanka,RG Sharma (INDIA),208*,2017
1,1,20,4,Mumbai (BS),v West Indies,RG Sharma (INDIA),162,2018
2,2,12,2,Cape Town,v South Africa,V Kohli (INDIA),160*,2018
3,3,13,4,Visakhapatnam,v West Indies,V Kohli (INDIA),157*,2018
4,4,15,8,Guwahati,v West Indies,RG Sharma (INDIA),152*,2018
5,5,18,2,Kanpur,v New Zealand,RG Sharma (INDIA),147,2017
6,6,21,2,Guwahati,v West Indies,V Kohli (INDIA),140,2018
7,7,15,4,Nottingham,v England,RG Sharma (INDIA),137*,2018
8,8,10,6,Sydney,v Australia,RG Sharma (INDIA),133,2019
9,9,20,3,Dambulla,v Sri Lanka,S Dhawan (INDIA),132*,2017
10,10,17,2,Colombo (RPS),v Sri Lanka,V Kohli (INDIA),131,2017
11,11,10,3,Cardiff,v England,SE Marsh (AUS),131,2018
12,12,11,3,Adelaide,v India,SE Marsh (AUS),131,2019
13,13,19,2,Centurion,v South Africa,V Kohli (INDIA),129*,2018
14,14,15,2,Dubai (DSC),v Hong Kong,S Dhawan (INDIA),127,2018
15,15,15,1,The Oval,v Sri Lanka,S Dhawan (INDIA),125,2017
16,16,11,5,Nagpur,v Australia,RG Sharma (INDIA),125,2017
17,17,16,2,Pallekele,v Sri Lanka,RG Sharma (INDIA),124*,2017
18,18,12,5,Indore,v India,AJ Finch (AUS),124,2017
19,19,12,4,Bengaluru,v India,DA Warner (AUS),124,2017
20,20,15,1,Birmingham,v Bangladesh,RG Sharma (INDIA),123*,2017
21,21,9,2,Mumbai,v New Zealand,V Kohli (INDIA),121,2017
22,22,11,4,Port Elizabeth,v South Africa,RG Sharma (INDIA),115,2018
23,23,16,2,Dubai (DSC),v Pakistan,S Dhawan (INDIA),114,2018
24,24,9,1,Kanpur,v New Zealand,V Kohli (INDIA),113,2017
25,25,10,0,Durban,v South Africa,V Kohli (INDIA),112,2018
26,26,12,2,Kingston,v West Indies,V Kohli (INDIA),111*,2017
27,27,7,4,Dubai (DSC),v Pakistan,RG Sharma (INDIA),111*,2018
28,28,9,0,Colombo (RPS),v Sri Lanka,V Kohli (INDIA),110*,2017
29,29,10,2,Johannesburg,v South Africa,S Dhawan (INDIA),109,2018
...,...,...,...,...,...,...,...,...
2132,18,-,-,Wellington,v New Zealand,SM Boland,DNB,2016
2133,19,-,-,Wellington,v New Zealand,JR Hazlewood,DNB,2016
2134,20,-,-,Providence,v West Indies,MA Starc,DNB,2016
2135,21,-,-,Providence,v West Indies,MS Wade,DNB,2016
2136,22,-,-,Providence,v West Indies,A Zampa,DNB,2016
2137,23,-,-,Providence,v West Indies,NM Lyon,DNB,2016
2138,24,-,-,Providence,v West Indies,JR Hazlewood,DNB,2016
2139,25,-,-,Basseterre,v West Indies,JR Hazlewood,DNB,2016
2140,26,-,-,Basseterre,v West Indies,A Zampa,DNB,2016
2141,27,-,-,Bridgetown,v West Indies,JR Hazlewood,DNB,2016
2142,28,-,-,Bridgetown,v West Indies,MA Starc,DNB,2016
2143,29,-,-,Bridgetown,v West Indies,MS Wade,DNB,2016
2144,30,-,-,Bridgetown,v West Indies,SM Boland,DNB,2016
2145,31,-,-,Bridgetown,v West Indies,JP Faulkner,DNB,2016
2146,32,-,-,Colombo (RPS),v Sri Lanka,A Zampa,DNB,2016
2147,33,-,-,Colombo (RPS),v Sri Lanka,JR Hazlewood,DNB,2016
2148,34,-,-,Dambulla,v Sri Lanka,JR Hazlewood,DNB,2016
2149,35,-,-,Dambulla,v Sri Lanka,A Zampa,DNB,2016
2150,36,-,-,Dambulla,v Sri Lanka,SM Boland,DNB,2016
2151,37,-,-,Dambulla,v Sri Lanka,JW Hastings,DNB,2016
2152,38,-,-,Dambulla,v Sri Lanka,JP Faulkner,DNB,2016
2153,39,-,-,Dambulla,v Sri Lanka,MA Starc,DNB,2016
2154,40,-,-,Pallekele,v Sri Lanka,A Zampa,DNB,2016
2155,41,-,-,Pallekele,v Sri Lanka,SM Boland,DNB,2016
2156,42,-,-,Pallekele,v Sri Lanka,AJ Finch,DNB,2016
2157,43,-,-,Pallekele,v Sri Lanka,MA Starc,DNB,2016
2158,44,-,-,Durban,v South Africa,A Zampa,DNB,2016
2159,45,-,-,Durban,v South Africa,JW Hastings,DNB,2016
2160,46,-,-,Durban,v South Africa,CP Tremain,DNB,2016
2161,47,-,-,Durban,v South Africa,DJ Worrall,DNB,2016

In [88]:
Ind_Aus_master_df_new =Ind_Aus_master_df.reset_index()

In [89]:

Ind_Aus_master_df_new['Runs']  = Ind_Aus_master_df_new['Runs'].str.split('*').str.get(0)

Ind_Aus_master_df_new.drop(['index'], axis=1, inplace=True)
Ind_Aus_master_df_new.columns

Index(['4s', '6s', 'Ground', 'Opposition', 'Player', 'Runs', 'Year'], dtype='object')

In [90]:
Ind_Aus_master_df_new.replace('DNB','0')

      4s  6s          Ground      Opposition             Player Runs  Year
0     13  12          Mohali     v Sri Lanka  RG Sharma (INDIA)  208  2017
1     20   4     Mumbai (BS)   v West Indies  RG Sharma (INDIA)  162  2018
2     12   2       Cape Town  v South Africa    V Kohli (INDIA)  160  2018
3     13   4   Visakhapatnam   v West Indies    V Kohli (INDIA)  157  2018
4     15   8        Guwahati   v West Indies  RG Sharma (INDIA)  152  2018
5     18   2          Kanpur   v New Zealand  RG Sharma (INDIA)  147  2017
6     21   2        Guwahati   v West Indies    V Kohli (INDIA)  140  2018
7     15   4      Nottingham       v England  RG Sharma (INDIA)  137  2018
8     10   6          Sydney     v Australia  RG Sharma (INDIA)  133  2019
9     20   3        Dambulla     v Sri Lanka   S Dhawan (INDIA)  132  2017
10    17   2   Colombo (RPS)     v Sri Lanka    V Kohli (INDIA)  131  2017
11    10   3         Cardiff       v England     SE Marsh (AUS)  131  2018
12    11   3        Adelaide         v India     SE Marsh (AUS)  131  2019
13    19   2       Centurion  v South Africa    V Kohli (INDIA)  129  2018
14    15   2     Dubai (DSC)     v Hong Kong   S Dhawan (INDIA)  127  2018
15    15   1        The Oval     v Sri Lanka   S Dhawan (INDIA)  125  2017
16    11   5          Nagpur     v Australia  RG Sharma (INDIA)  125  2017
17    16   2       Pallekele     v Sri Lanka  RG Sharma (INDIA)  124  2017
18    12   5          Indore         v India     AJ Finch (AUS)  124  2017
19    12   4       Bengaluru         v India    DA Warner (AUS)  124  2017
20    15   1      Birmingham    v Bangladesh  RG Sharma (INDIA)  123  2017
21     9   2          Mumbai   v New Zealand    V Kohli (INDIA)  121  2017
22    11   4  Port Elizabeth  v South Africa  RG Sharma (INDIA)  115  2018
23    16   2     Dubai (DSC)      v Pakistan   S Dhawan (INDIA)  114  2018
24     9   1          Kanpur   v New Zealand    V Kohli (INDIA)  113  2017
25    10   0          Durban  v South Africa    V Kohli (INDIA)  112  2018
26    12   2        Kingston   v West Indies    V Kohli (INDIA)  111  2017
27     7   4     Dubai (DSC)      v Pakistan  RG Sharma (INDIA)  111  2018
28     9   0   Colombo (RPS)     v Sri Lanka    V Kohli (INDIA)  110  2017
29    10   2    Johannesburg  v South Africa   S Dhawan (INDIA)  109  2018
...   ..  ..             ...             ...                ...  ...   ...
2132   -   -      Wellington   v New Zealand          SM Boland    0  2016
2133   -   -      Wellington   v New Zealand       JR Hazlewood    0  2016
2134   -   -      Providence   v West Indies           MA Starc    0  2016
2135   -   -      Providence   v West Indies            MS Wade    0  2016
2136   -   -      Providence   v West Indies            A Zampa    0  2016
2137   -   -      Providence   v West Indies            NM Lyon    0  2016
2138   -   -      Providence   v West Indies       JR Hazlewood    0  2016
2139   -   -      Basseterre   v West Indies       JR Hazlewood    0  2016
2140   -   -      Basseterre   v West Indies            A Zampa    0  2016
2141   -   -      Bridgetown   v West Indies       JR Hazlewood    0  2016
2142   -   -      Bridgetown   v West Indies           MA Starc    0  2016
2143   -   -      Bridgetown   v West Indies            MS Wade    0  2016
2144   -   -      Bridgetown   v West Indies          SM Boland    0  2016
2145   -   -      Bridgetown   v West Indies        JP Faulkner    0  2016
2146   -   -   Colombo (RPS)     v Sri Lanka            A Zampa    0  2016
2147   -   -   Colombo (RPS)     v Sri Lanka       JR Hazlewood    0  2016
2148   -   -        Dambulla     v Sri Lanka       JR Hazlewood    0  2016
2149   -   -        Dambulla     v Sri Lanka            A Zampa    0  2016
2150   -   -        Dambulla     v Sri Lanka          SM Boland    0  2016
2151   -   -        Dambulla     v Sri Lanka        JW Hastings    0  2016
2152   -   -        Dambulla     v Sri Lanka        JP Faulkner    0  2016
2153   -   -        Dambulla     v Sri Lanka           MA Starc    0  2016
2154   -   -       Pallekele     v Sri Lanka            A Zampa    0  2016
2155   -   -       Pallekele     v Sri Lanka          SM Boland    0  2016
2156   -   -       Pallekele     v Sri Lanka           AJ Finch    0  2016
2157   -   -       Pallekele     v Sri Lanka           MA Starc    0  2016
2158   -   -          Durban  v South Africa            A Zampa    0  2016
2159   -   -          Durban  v South Africa        JW Hastings    0  2016
2160   -   -          Durban  v South Africa         CP Tremain    0  2016
2161   -   -          Durban  v South Africa         DJ Worrall    0  2016

[2162 rows x 7 columns]

In [91]:
Ind_Aus_master_df_new['Player']  = Ind_Aus_master_df_new['Player'].str.split().str.get(0)+Ind_Aus_master_df_new['Player'].str.split().str.get(1)
Ind_Aus_master_df_new.Player.unique()

array(['RGSharma', 'VKohli', 'SDhawan', 'SEMarsh', 'AJFinch', 'DAWarner',
       'AMRahane', 'ATRayudu', 'TMHead', 'SSIyer', 'MSDhoni', 'MPStoinis',
       'HHPandya', 'PSPHandscomb', 'KMJadhav', 'KDKarthik', 'SPDSmith',
       'GJMaxwell', 'KLRahul', 'UTKhawaja', 'MRMarsh', 'BKumar',
       'YuvrajSingh', 'MKPandey', 'DJMShort', 'ATCarey', 'ACAgar',
       'SKRaina', 'VShankar', 'CALynn', 'TDPaine', 'NMCoulter-Nile',
       'JPFaulkner', 'RAJadeja', 'RRPant', 'SNThakur', 'AZampa', 'MSWade',
       'KuldeepYadav', 'AJTye', 'YSChahal', 'MCHenriques', 'CLWhite',
       'JARichardson', 'KWRichardson', 'NMLyon', 'PJCummins', 'DLChahar',
       'MAStarc', 'JJBumrah', 'JRHazlewood', 'PMSiddle', 'ShubmanGill',
       'MohammedShami', 'ARPatel', 'MGNeser', 'KKAhmed', 'UTYadav',
       'BStanlake', 'JPBehrendorff', 'RAshwin', 'HWRCartwright', 'SKaul',
       'WashingtonSundar', 'MohammedSiraj', 'DSKulkarni',
       'HarbhajanSingh', 'AMishra', 'STRBinny', 'JYadav', 'MMSharma',
       'SRTendulkar', 'GGambhir', 'PKumar', 'VSehwag', 'MVijay',
       'SSTiwary', 'RVinay', 'ANehra', 'ISharma', 'MMPatel', 'GJBailey',
       'MJClarke', 'RTPonting', 'SRWatson', 'PJHughes', 'MEKHussey',
       'ACVoges', 'BJHaddin', 'DJHussey', 'NMHauritz', 'MGJohnson',
       'CJMcKay', 'BWHilfenhaus', 'JRHopes', 'GAManou', 'XJDoherty',
       'BLee', 'DEBollinger', 'JWHastings', 'SWTait', 'JJKrejza',
       'PAPatel', 'RVUthappa', 'YKPathan', 'ZKhan', 'WPSaha', 'PPChawla',
       'JABurns', 'CPTremain', 'DJWorrall', 'SMBoland', 'SDHeazlett',
       'JLPattinson', 'JMMennie'], dtype=object)

In [92]:
current_Player_list =['RGSharma', 'VKohli', 'SDhawan', 'SEMarsh', 'AJFinch', 
       'ATRayudu', 'TMHead',  'MSDhoni', 'MPStoinis',
       'PSPHandscomb', 'KMJadhav', 'KDKarthik', 
       'GJMaxwell', 'KLRahul', 'UTKhawaja',  'BKumar',
      'DJMShort', 'ATCarey','VShankar', 'NMCoulter-Nile',
       'RRPant', 'PJCummins']

In [93]:
Ind_Aus_master_df_new = Ind_Aus_master_df_new[Ind_Aus_master_df_new['Player'].isin(current_Player_list)]

In [94]:
Ind_Aus_master_df_filtered = Ind_Aus_master_df_new.reset_index()

In [95]:

Ind_Aus_master_df_filtered.replace('DNB','0')
Ind_Aus_master_df_filtered['Runs']
#Ind_Aus_master_df_filtered = Ind_Aus_master_df_filtered[0:888]
#Ind_Aus_master_df_filtered

0      208
1      162
2      160
3      157
4      152
5      147
6      140
7      137
8      133
9      132
10     131
11     131
12     131
13     129
14     127
15     125
16     125
17     124
18     124
19     123
20     121
21     115
22     114
23     113
24     112
25     111
26     111
27     110
28     109
29     107
      ...
867      2
868      2
869      1
870      1
871      1
872      1
873      1
874      1
875      0
876      0
877      0
878      0
879      0
880      0
881      0
882      0
883      0
884      0
885      0
886      0
887      0
888    DNB
889    DNB
890    DNB
891    DNB
892    DNB
893    DNB
894    DNB
895    DNB
896    DNB
Name: Runs, Length: 897, dtype: object

In [96]:
Ind_Aus_master_df_filtered.drop(['4s','6s','index'], axis=1, inplace=True)

In [97]:
testCases_runs_hyd = pd.read_csv("C:\\Users\\sushanth\\Desktop\\testCases_runs_hyd_new.csv", sep=",", header = 0, engine='python', encoding ="utf-8", skipinitialspace=True)
testCases_runs_ranchi = pd.read_csv("C:\\Users\\sushanth\\Desktop\\testCases_runs_ranchi_new.csv", sep=",", header = 0, engine='python', encoding ="utf-8", skipinitialspace=True)
testCases_runs_delhi = pd.read_csv("C:\\Users\\sushanth\\Desktop\\testCases_runs_delhi_new.csv", sep=",", header = 0, engine='python', encoding ="utf-8", skipinitialspace=True)
testCases_runs_nagpur = pd.read_csv("C:\\Users\\sushanth\\Desktop\\testCases_runs_nagpur_new.csv", sep=",", header = 0, engine='python', encoding ="utf-8", skipinitialspace=True)
testCases_runs_mohali = pd.read_csv("C:\\Users\\sushanth\\Desktop\\testCases_runs_mohali_new.csv", sep=",", header = 0, engine='python', encoding ="utf-8", skipinitialspace=True)
testCases_runs_hyd.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21 entries, 0 to 20
Data columns (total 4 columns):
Ground        21 non-null object
Opposition    21 non-null object
Player        21 non-null object
Year          21 non-null int64
dtypes: int64(1), object(3)
memory usage: 752.0+ bytes

In [98]:

Ind_Aus_master_df_filtered = Ind_Aus_master_df_filtered.append([testCases_runs_hyd,testCases_runs_ranchi,testCases_runs_delhi,testCases_runs_nagpur,testCases_runs_mohali])
Ind_Aus_master_df_filtered.reset_index()

      index          Ground      Opposition        Player Runs  Year
0         0          Mohali     v Sri Lanka      RGSharma  208  2017
1         1     Mumbai (BS)   v West Indies      RGSharma  162  2018
2         2       Cape Town  v South Africa        VKohli  160  2018
3         3   Visakhapatnam   v West Indies        VKohli  157  2018
4         4        Guwahati   v West Indies      RGSharma  152  2018
5         5          Kanpur   v New Zealand      RGSharma  147  2017
6         6        Guwahati   v West Indies        VKohli  140  2018
7         7      Nottingham       v England      RGSharma  137  2018
8         8          Sydney     v Australia      RGSharma  133  2019
9         9        Dambulla     v Sri Lanka       SDhawan  132  2017
10       10   Colombo (RPS)     v Sri Lanka        VKohli  131  2017
11       11         Cardiff       v England       SEMarsh  131  2018
12       12        Adelaide         v India       SEMarsh  131  2019
13       13       Centurion  v South Africa        VKohli  129  2018
14       14     Dubai (DSC)     v Hong Kong       SDhawan  127  2018
15       15        The Oval     v Sri Lanka       SDhawan  125  2017
16       16          Nagpur     v Australia      RGSharma  125  2017
17       17       Pallekele     v Sri Lanka      RGSharma  124  2017
18       18          Indore         v India       AJFinch  124  2017
19       19      Birmingham    v Bangladesh      RGSharma  123  2017
20       20          Mumbai   v New Zealand        VKohli  121  2017
21       21  Port Elizabeth  v South Africa      RGSharma  115  2018
22       22     Dubai (DSC)      v Pakistan       SDhawan  114  2018
23       23          Kanpur   v New Zealand        VKohli  113  2017
24       24          Durban  v South Africa        VKohli  112  2018
25       25        Kingston   v West Indies        VKohli  111  2017
26       26     Dubai (DSC)      v Pakistan      RGSharma  111  2018
27       27   Colombo (RPS)     v Sri Lanka        VKohli  110  2017
28       28    Johannesburg  v South Africa       SDhawan  109  2018
29       29       Melbourne       v England       AJFinch  107  2018
...     ...             ...             ...           ...  ...   ...
972      12          Nagpur         v India       AJFinch  NaN  2019
973      13          Nagpur         v India        TMHead  NaN  2019
974      14          Nagpur         v India     MPStoinis  NaN  2019
975      15          Nagpur         v India  PSPHandscomb  NaN  2019
976      16          Nagpur         v India     GJMaxwell  NaN  2019
977      17          Nagpur         v India     UTKhawaja  NaN  2019
978      18          Nagpur         v India      DJMShort  NaN  2019
979      19          Nagpur         v India       ATCarey  NaN  2019
980      20          Nagpur         v India     PJCummins  NaN  2019
981       0          Mohali     v Australia      RGSharma  NaN  2019
982       1          Mohali     v Australia        VKohli  NaN  2019
983       2          Mohali     v Australia       SDhawan  NaN  2019
984       3          Mohali     v Australia      ATRayudu  NaN  2019
985       4          Mohali     v Australia       MSDhoni  NaN  2019
986       5          Mohali     v Australia      KMJadhav  NaN  2019
987       6          Mohali     v Australia       KLRahul  NaN  2019
988       7          Mohali     v Australia     KDKarthik  NaN  2019
989       8          Mohali     v Australia      KMJadhav  NaN  2019
990       9          Mohali     v Australia        RRPant  NaN  2019
991      10          Mohali     v Australia      VShankar  NaN  2019
992      11          Mohali         v India       SEMarsh  NaN  2019
993      12          Mohali         v India       AJFinch  NaN  2019
994      13          Mohali         v India        TMHead  NaN  2019
995      14          Mohali         v India     MPStoinis  NaN  2019
996      15          Mohali         v India  PSPHandscomb  NaN  2019
997      16          Mohali         v India     GJMaxwell  NaN  2019
998      17          Mohali         v India     UTKhawaja  NaN  2019
999      18          Mohali         v India      DJMShort  NaN  2019
1000     19          Mohali         v India       ATCarey  NaN  2019
1001     20          Mohali         v India     PJCummins  NaN  2019

[1002 rows x 6 columns]

In [99]:
Ind_Aus_master_df_filtered_Opposition = pd.get_dummies(Ind_Aus_master_df_filtered['Opposition'],prefix="Opposition")
#Adding the results to the master dataframe
Ind_Aus_master_df_filtered = pd.concat([Ind_Aus_master_df_filtered,Ind_Aus_master_df_filtered_Opposition],axis=1)
Ind_Aus_master_df_filtered.drop(['Opposition'],axis=1,inplace=True)



Ind_Aus_master_df_filtered_Ground = pd.get_dummies(Ind_Aus_master_df_filtered['Ground'],prefix="Ground")
#Adding the results to the master dataframe
Ind_Aus_master_df_filtered = pd.concat([Ind_Aus_master_df_filtered,Ind_Aus_master_df_filtered_Ground],axis=1)
Ind_Aus_master_df_filtered.drop(['Ground'],axis=1,inplace=True)



Ind_Aus_master_df_filtered_Year = pd.get_dummies(Ind_Aus_master_df_filtered['Year'],prefix="Year")
#Adding the results to the master dataframe
Ind_Aus_master_df_filtered = pd.concat([Ind_Aus_master_df_filtered,Ind_Aus_master_df_filtered_Year],axis=1)
Ind_Aus_master_df_filtered.drop(['Year'],axis=1,inplace=True)

Ind_Aus_master_df_filtered_Player = pd.get_dummies(Ind_Aus_master_df_filtered['Player'],prefix="Player")
#Adding the results to the master dataframe
Ind_Aus_master_df_filtered = pd.concat([Ind_Aus_master_df_filtered,Ind_Aus_master_df_filtered_Player],axis=1)
Ind_Aus_master_df_filtered.drop(['Player'],axis=1,inplace=True)

In [100]:
Ind_Aus_master_df_filtered

,Runs,Opposition_v Afghanistan,Opposition_v Australia,Opposition_v Bangladesh,Opposition_v England,Opposition_v Hong Kong,Opposition_v India,Opposition_v Ireland,Opposition_v Netherlands,Opposition_v New Zealand,...,Player_PJCummins,Player_PSPHandscomb,Player_RGSharma,Player_RRPant,Player_SDhawan,Player_SEMarsh,Player_TMHead,Player_UTKhawaja,Player_VKohli,Player_VShankar
0,208,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
1,162,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
2,160,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
3,157,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
4,152,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
5,147,0,0,0,0,0,0,0,0,1,...,0,0,1,0,0,0,0,0,0,0
6,140,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
7,137,0,0,0,1,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
8,133,0,1,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
9,132,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
10,131,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
11,131,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
12,131,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,1,0,0,0,0
13,129,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
14,127,0,0,0,0,1,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
15,125,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
16,125,0,1,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
17,124,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
18,124,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
19,123,0,0,1,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
20,121,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,1,0
21,115,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
22,114,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
23,113,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,1,0
24,112,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
25,111,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
26,111,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
27,110,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
28,109,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
29,107,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12,NaN,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
13,NaN,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,1,0,0,0
14,NaN,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
15,NaN,0,0,0,0,0,1,0,0,0,...,0,1,0,0,0,0,0,0,0,0
16,NaN,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
17,NaN,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,1,0,0
18,NaN,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
19,NaN,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
20,NaN,0,0,0,0,0,1,0,0,0,...,1,0,0,0,0,0,0,0,0,0
0,NaN,0,1,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
1,NaN,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
2,NaN,0,1,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
3,NaN,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,NaN,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5,NaN,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
6,NaN,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7,NaN,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
8,NaN,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9,NaN,0,1,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
10,NaN,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
11,NaN,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,1,0,0,0,0
12,NaN,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
13,NaN,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,1,0,0,0
14,NaN,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
15,NaN,0,0,0,0,0,1,0,0,0,...,0,1,0,0,0,0,0,0,0,0
16,NaN,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
17,NaN,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,1,0,0
18,NaN,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
19,NaN,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
20,NaN,0,0,0,0,0,1,0,0,0,...,1,0,0,0,0,0,0,0,0,0

In [101]:
# Putting feature variable to X
# Putting feature variable to X
Ind_Aus_master_df_filtered_new = Ind_Aus_master_df_filtered.reset_index()
Ind_Aus_master_df_filtered_new.drop(['index'], axis=1, inplace=True)
Ind_Aus_master_df_filtered_new["Runs"]= Ind_Aus_master_df_filtered_new["Runs"].replace('DNB', '0') 
Ind_Aus_master_df_filtered_new['Runs'].fillna('0', inplace=True)

#Ind_Aus_master_df_filtered_new['Runs'] = Ind_Aus_master_df_filtered_new['Runs'].astype(int)
X_train = Ind_Aus_master_df_filtered_new[0:897].drop(['Runs'],axis=1)

# Putting response variable to y
y_train = Ind_Aus_master_df_filtered_new[0:897]['Runs']

X_test_hyd = Ind_Aus_master_df_filtered_new[897:918].drop(['Runs'],axis=1)

# Putting response variable to y
y_test_hyd = Ind_Aus_master_df_filtered_new[897:918]['Runs']

X_test_ranchi = Ind_Aus_master_df_filtered_new[918:939].drop(['Runs'],axis=1)

# Putting response variable to y
y_test_ranchi = Ind_Aus_master_df_filtered_new[918:939]['Runs']

X_test_delhi = Ind_Aus_master_df_filtered_new[939:960].drop(['Runs'],axis=1)

# Putting response variable to y
y_test_delhi = Ind_Aus_master_df_filtered_new[939:960]['Runs']

X_test_nagpur = Ind_Aus_master_df_filtered_new[960:981].drop(['Runs'],axis=1)

# Putting response variable to y
y_test_nagpur = Ind_Aus_master_df_filtered_new[960:981]['Runs']

X_test_mohali = Ind_Aus_master_df_filtered_new[981:].drop(['Runs'],axis=1)

# Putting response variable to y
y_test_mohali= Ind_Aus_master_df_filtered_new[981:]['Runs']



y_train

0      208
1      162
2      160
3      157
4      152
5      147
6      140
7      137
8      133
9      132
10     131
11     131
12     131
13     129
14     127
15     125
16     125
17     124
18     124
19     123
20     121
21     115
22     114
23     113
24     112
25     111
26     111
27     110
28     109
29     107
      ...
867      2
868      2
869      1
870      1
871      1
872      1
873      1
874      1
875      0
876      0
877      0
878      0
879      0
880      0
881      0
882      0
883      0
884      0
885      0
886      0
887      0
888      0
889      0
890      0
891      0
892      0
893      0
894      0
895      0
896      0
Name: Runs, Length: 897, dtype: object

In [102]:
Ind_Aus_master_df_filtered['Runs'][890]

'DNB'

In [103]:
from sklearn.linear_model import LinearRegression
# Representing LinearRegression as lr(Creating LinearRegression Object)
lm = LinearRegression()
# fit the model to the training data
lm.fit(X_train,y_train)
# Making predictions using the model
y_pred_hyd = lm.predict(X_test_hyd)
y_pred_ranchi = lm.predict(X_test_ranchi)
y_pred_delhi = lm.predict(X_test_delhi)
y_pred_nagpur = lm.predict(X_test_nagpur)
y_pred_mohali = lm.predict(X_test_mohali)

In [104]:
y_pred_overall =[a+b+c+d+e for a,b,c,d,e in zip(y_pred_hyd, y_pred_ranchi,y_pred_delhi,y_pred_nagpur,y_pred_mohali)]
y_pred_overall

[124.5,
 162.0,
 54.5,
 42.0,
 13.25,
 -49.25,
 -113.0,
 -41.75,
 -49.25,
 -74.875,
 -71.125,
 51.5,
 35.875,
 -12.25,
 -29.125,
 -54.75,
 -64.75,
 30.25,
 -31.0,
 -49.75,
 -158.5]

#### 2nd player in the list i.e Kohli will score the maximum number of runs in the series
#### Top run scorers of the series:
#### 1.Virat Kohli
#### 2.rohit sharma
#### 3..Shikhar Dhawan
#### 4.Shaun Marsh
#### 5.Ambati Rayudu

#### Top three run scores for India: 1.Kohli, 2.Rohit, 3. Dhawan

#### Top three run scores for Aus: 1.Shaun Marsh, 2.Aaron Finch, 3.Usman Khawaja